server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: dhyang02-java17-restdocs-demo
  data:
    web:
      pageable:
        one-indexed-parameters: on
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: on

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
